# Generated by Django 2.0.1 on 2018-01-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='pub_date',
        ),
    ]
